### PR TITLE
News scenarios for speedbit

### PR DESCRIPTION
**Pull request by therealfnadeau**
A new file of scenarios for Speedbit Demo

### CODE REVIEW

**Comment by therealfnadeau** [comment]
There are to files: Scenarios for an ORG Indexfull and Scenarios for an ORG Indexless

**Comment by erocheleau** [comment]
@therealfnadeau you would need to add a description please, especially since you modified some code.
Just paste your commit message about the IP adresses in the description
+ Adding scenarios.

**Comment by francoislg** [comment]
Why is there a `Submodule uabot added at 68a7ed` change in there.

**Comment by therealfnadeau** [comment]
For the Submodule uabot added at 68a7ed Seriously I really don't know why it's there...

**Pull request merged**
