### PR TITLE
News Scenarios for CapricornCafe

### PR DESCRIPTION
**Pull request by therealfnadeau**

### CODE REVIEW

**Comment by erocheleau** [comment]
When @therealfnadeau will have tested locally his new scenario files, then I will merge.

**Comment by lbenie** [comment]
is there a way to test scenarios with travis ?

**Comment by erocheleau** [comment]
I've been thinking about it, not really since they all require api keys etc.
I think the best we can setup is test mocks for the go functions

**Comment by lbenie** [comment]
I should probably give go a try and try to implement these 🎅

**Comment by therealfnadeau** [comment]
Would be a great idea ;)

**Pull request closed without merging**
